name: ecommerceapp
description: "The official mobile application for FOS Productions, providing a seamless e-commerce experience."
publish_to: 'none'

version: 1.0.4+11

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # State Management
  get: ^4.6.6
  
  # Local Storage & Caching
  shared_preferences: ^2.2.2
  get_storage: ^2.1.1
  hive: ^2.2.0
  hive_flutter: ^1.1.0
  
  # Network
  dio: ^5.4.0
  
  # Utils
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.2
  package_info_plus: ^8.3.1
  share_plus: ^10.1.4
  webview_flutter: ^4.13.0
  path_provider: ^2.1.5
  flutter_svg: ^2.2.3
  
  # Location
  geolocator: ^13.0.4
  permission_handler: ^11.4.0
  geocoding: ^4.0.0

  # Payment
  flutter_stripe: ^11.5.0
  sign_in_with_apple: ^7.0.1
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  device_preview: ^1.2.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/fos_logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/fos_logo.jpg
    - assets/images/google.png
